# Site settings
title: Joe Sergenian
tagline: portfolio
description: Online portfolio for Joe Sergenian
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.joesergenian.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Collections
# Add new slides as HTML files inside the _panels folder
collections:
  - panels